const bakgrunnsaarsakTabellBogG: { value: string; label: string }[] = [
  { value: "Manglende merking, varsling, skilting", label: "Manglende merking, varsling, skilting" },
  { value: "Mangelfulle sikkerhetsrutiner", label: "Mangelfulle sikkerhetsrutiner" },
  { value: "Utilstrekkelig sikring", label: "Utilstrekkelig sikring" },
  { value: "Vernetiltak ikke/delvis gjennomført", label: "Vernetiltak ikke/delvis gjennomført" },
  { value: "Verneutstyr satt ut av funksjon", label: "Verneutstyr satt ut av funksjon" },
  { value: "Verneutstyr fjernet", label: "Verneutstyr fjernet" },
  { value: "Uautorisert bruk av utstyr", label: "Uautorisert bruk av utstyr" },
  { value: "Defekt utstyr", label: "Defekt utstyr" },
  { value: "Feil bruk eller tap av kontroll (helt eller delvis) over maskin, transportmiddel, utstyr for å forflytte materiale, håndholdt verktøy, gjenstand, dyr", label: "Feil bruk eller tap av kontroll (helt eller delvis) over maskin, transportmiddel, utstyr for å forflytte materiale, håndholdt verktøy, gjenstand, dyr" },
  { value: "Feil pålasting", label: "Feil pålasting" },
  { value: "Feil plassering", label: "Feil plassering" },
  { value: "Feil løfting", label: "Feil løfting" },
  { value: "Feil utførelse av oppgaven", label: "Feil utførelse av oppgaven" },
  { value: "Mangelfull opplæring", label: "Mangelfull opplæring" },
  { value: "Angrepet/truet av en annen person", label: "Angrepet/truet av en annen person" },
  { value: "Uforsvarlig «lek», spøk eller veddemål", label: "Uforsvarlig «lek», spøk eller veddemål" },
  { value: "Påvirkning av alkohol/andre rusmidler", label: "Påvirkning av alkohol/andre rusmidler" },
  { value: "Bedriftsidrett eller lignende", label: "Bedriftsidrett eller lignende" },
  { value: "Avvik som følge av elektriske problemer, eksplosjon, brann", label: "Avvik som følge av elektriske problemer, eksplosjon, brann" },
  { value: "Avvik som følge av overstrømning, velt, lekkasje, utstrømning, avdamping, utstråling", label: "Avvik som følge av overstrømning, velt, lekkasje, utstrømning, avdamping, utstråling" },
  { value: "Bristing, sprengning, oppsplitting, glidning, fall, ytre faktor kollapser", label: "Bristing, sprengning, oppsplitting, glidning, fall, ytre faktor kollapser" },
  { value: "Glidning, snubling", label: "Glidning, snubling" },
  { value: "Kroppsbevegelse uten fysisk belastning (som vanligvis fører til en ytre skade)", label: "Kroppsbevegelse uten fysisk belastning (som vanligvis fører til en ytre skade)" },
  { value: "Kroppsbevegelse under eller med fysisk belastning (som vanligvis fører til en indre skade)", label: "Kroppsbevegelse under eller med fysisk belastning (som vanligvis fører til en indre skade)" },
  { value: "Tistedeværelse ved vold, aggresjon, trussel", label: "Tistedeværelse ved vold, aggresjon, trussel" },
  { value: "Alternativene passer ikke", label: "Alternativene passer ikke" },
];
export default bakgrunnsaarsakTabellBogG
