FROM node:16-alpine

RUN apk add tzdata
RUN cp /usr/share/zoneinfo/Europe/Oslo /etc/localtime
RUN echo "Europe/Oslo" >  /etc/timezone

ENV NODE_ENV development

VOLUME ["app"]

WORKDIR /app

EXPOSE 3001 3000

CMD ["yarn", "dev"]
