ingresses:
- "https://yrkesskade-skjema.dev.intern.nav.no"
env:
- name: DECORATOR_URL
  value: "https://dekoratoren.dev.nav.no"
- name: DECORATOR_ENV
  value: "dev"
externals:
  - "dekoratoren.dev.nav.no"
