ingresses:
- "https://skademelding.dev.nav.no"
env:
- name: DECORATOR_URL
  value: "https://dekoratoren.dev.nav.no"
- name: DECORATOR_ENV
  value: "dev"
- name: NODE_ENV
  value: dev
- name: ENV
  value: dev
- name: DOKGEN_URL
  value: https://yrkesskade-dokgen.dev.intern.nav.no
externals:
  - "dekoratoren.dev.nav.no"
