ingresses:
- "https://skademelding.dev.nav.no"
env:
- name: DECORATOR_URL
  value: "https://dekoratoren.dev.nav.no"
- name: DECORATOR_ENV
  value: "dev"
- name: APP_INGRESS
  value: "https://yrkesskade-skjema.dev.nav.no"
- name: LOGIN_URL
  value: https://loginservice.dev.nav.no/login?redirect=
- name: NODE_ENV
  value: dev
- name: ENV
  value: dev
- name: TOKENX_AUDIENCE
  value: "dev-gcp:yrkesskade:yrkesskade-melding-api"
- name: API_URL
  value: https://yrkesskade-melding-api.dev.intern.nav.no
externals:
  - "dekoratoren.dev.nav.no"
