ingresses:
- "https://skademelding.nav.no"
env:
- name: DECORATOR_URL
  value: "https://dekoratoren.nav.no"
- name: DECORATOR_ENV
  value: "prod"
- name: NODE_ENV
  value: prod
- name: ENV
  value: prod
- name: DOKGEN_URL
  value: https://yrkesskade-dokgen.intern.nav.no
externals:
  - "dekoratoren.nav.no"
