ingresses:
- "https://skademelding.nav.no"
env:
- name: DECORATOR_URL
  value: "https://dekoratoren.nav.no"
- name: DECORATOR_ENV
  value: "prod"
- name: NODE_ENV
  value: prod
- name: ENV
  value: production
- name: TOKENX_AUDIENCE
  value: "prod-gcp:yrkesskade:yrkesskade-melding-api"
- name: API_URL
  value: https://yrkesskade-melding-api.intern.nav.no
- name: DOKGEN_URL
  value: https://yrkesskade-dokgen.intern.nav.no
externals:
  - "dekoratoren.nav.no"
