enum accidentType {
  A1 = "Støt/treff av gjenstand",
  A2 = " Sammenstøt/påkjørsel",
  A3 = "Velt",
  A4 = "Klemt/fanget",
  A5 = "Fall",
  A6 = "Stukket/kuttet av skarp/spiss gjenstand",
  A7 = "Elektrisk spenning",
  A8 = "Høy/lav temperatur",
  A9 = "Kjemikalier",
  A10 = "Eksplosjon, sprenging, brann",
  A11 = "Trusler om vold",
  A12 = "Påført voldsskade",
  A13 = "Annet",
}

enum accidentBackground {
  B1 = "Manglende merking, varsling, skilting",
  B2 = "Mangelfulle sikkerhetsrutiner",
  B3 = "Utilstrekkelig sikring",
  B4 = "Vernetiltak ikke/delvis gjennomført",
  B5 = "Verneutstyr satt ut av funksjon",
  B6 = "Verneutstyr fjernet",
  B7 = "Uautorisert bruk av utstyr",
  B8 = "Defekt utstyr",
  B9 = "Feil bruk av maskiner og utstyr",
  B10 = "Feil pålasting",
  B11 = "Feil plassering",
  B12 = "Feil løfting",
  B13 = "Feil utførelse av oppgaven",
  B14 = "Mangelfull opplæring",
  B15 = "Angrepet/truet av en annen person",
  B16 = "Uforsvarlig «lek», spøk eller veddemål",
  B17 = "Påvirkning av alkohol/andre rusmidler",
  B18 = "Bedriftsidrett e l",
  B19 = "Annet",
}

enum injuryType {
  C1 = "Bløtdelsskade uten sår (klemskade)",
  C2 = "Sårskade",
  C3 = "Tap av legemsdel",
  C4 = "Forstuing, forvridning",
  C5 = "Knokkelbrudd",
  C6 = "Varmeskade",
  C7 = "Kuldeskade",
  C8 = "Etsing",
  C9 = "Akutt forgiftning",
  C10 = "Psykiske ettervirkninger",
  C11 = "Annet",
}

enum injuredBodypart {
  D1 = "Hode",
  D2 = "Ansikt",
  D3 = "Øye, venstre",
  D4 = "Øye, høyre",
  D5 = "Øre, venstre",
  D6 = "Øre, høyre",
  D7 = "Tenner",
  D8 = "Hals/nakke",
  D9 = "Rygg",
  D10 = "Ribben/skulderblad",
  D11 = "Brystkasse/lunger/hjerte /spiserør",
  D12 = "Mave/bekken/fordøyelsesorganer/nyre/urinveier",
  D13 = "Skulder, venstre",
  D14 = "Skulder, høyre",
  D15 = "Arm/albue, venstre",
  D16 = "Arm/albue, høyre",
  D17 = "Håndledd, venstre",
  D18 = "Håndledd, høyre",
  D19 = "Hånd, venstre",
  D20 = "Hånd, høyre",
  D21 = "Fingre, venstre",
  D22 = "Fingre, høyre",
  D23 = "Hofte, venstre",
  D24 = "Hofte høyre",
  D25 = "Ben m/kne, venstre",
  D26 = "Ben m/kne, høyre",
  D27 = "Ankel, venstre",
  D28 = "Ankel, høyre",
  D29 = "Fot, venstre",
  D30 = "Fot, høyre",
  D31 = "Tær, venstre",
  D32 = "Tær, høyre",
  D33 = "Hele kroppen (allmenn forgiftning,allmenn nedkjøling, e.l.)",
}

export { injuredBodypart, accidentType, accidentBackground, injuryType };
