const stillingstitler: {value: string, label: string}[] = [
  { value: 'Politikere', label: 'Politikere' },
  { value: 'Toppledere i offentlig administrasjon', label: 'Toppledere i offentlig administrasjon' },
  { value: 'Toppledere i interesseorganisasjoner', label: 'Toppledere i interesseorganisasjoner' },
  { value: 'Administrerende direktører', label: 'Administrerende direktører' },
  { value: 'Finans- og økonomisjefer', label: 'Finans- og økonomisjefer' },
  { value: 'Personalsjefer', label: 'Personalsjefer' },
  { value: 'Strategi- og planleggingssjefer', label: 'Strategi- og planleggingssjefer' },
  { value: 'Andre administrative ledere', label: 'Andre administrative ledere' },
  { value: 'Salgs- og markedssjefer', label: 'Salgs- og markedssjefer' },
  { value: 'PR- og informasjonssjefer', label: 'PR- og informasjonssjefer' },
  { value: 'Forsknings- og utviklingsledere', label: 'Forsknings- og utviklingsledere' },
  { value: 'Ledere i skogbruk, gartnerier mv.', label: 'Ledere i skogbruk, gartnerier mv.' },
  { value: 'Ledere innen akvakultur mv.', label: 'Ledere innen akvakultur mv.' },
  { value: 'Ledere av industriproduksjon mv.', label: 'Ledere av industriproduksjon mv.' },
  { value: 'Ledere av olje- og gassutvinning mv.', label: 'Ledere av olje- og gassutvinning mv.' },
  { value: 'Ledere av bygge- og anleggsvirksomhet', label: 'Ledere av bygge- og anleggsvirksomhet' },
  { value: 'Ledere av logistikk og transport mv.', label: 'Ledere av logistikk og transport mv.' },
  { value: 'Ledere av IKT-enheter', label: 'Ledere av IKT-enheter' },
  { value: 'Ledere av omsorgstjenester for barn', label: 'Ledere av omsorgstjenester for barn' },
  { value: 'Ledere av helsetjenester', label: 'Ledere av helsetjenester' },
  { value: 'Ledere av eldreomsorg', label: 'Ledere av eldreomsorg' },
  { value: 'Ledere av sosialomsorg', label: 'Ledere av sosialomsorg' },
  { value: 'Ledere av utdanning og undervisning', label: 'Ledere av utdanning og undervisning' },
  { value: 'Ledere av forsikring og finansvirksomhet', label: 'Ledere av forsikring og finansvirksomhet' },
  { value: 'Andre ledere av produksjon og tjenesteyting', label: 'Andre ledere av produksjon og tjenesteyting' },
  { value: 'Hotellsjefer', label: 'Hotellsjefer' },
  { value: 'Restaurantsjefer', label: 'Restaurantsjefer' },
  { value: 'Varehandelssjefer', label: 'Varehandelssjefer' },
  { value: 'Sports-, rekreasjons- og kultursenterledere', label: 'Sports-, rekreasjons- og kultursenterledere' },
  { value: 'Andre daglige ledere i tjenesteytende virksomheter', label: 'Andre daglige ledere i tjenesteytende virksomheter' },
  { value: 'Fysikere og astronomer', label: 'Fysikere og astronomer' },
  { value: 'Meteorologer', label: 'Meteorologer' },
  { value: 'Kjemikere', label: 'Kjemikere' },
  { value: 'Geologer og geofysikere', label: 'Geologer og geofysikere' },
  { value: 'Matematikere, statistikere mv.', label: 'Matematikere, statistikere mv.' },
  { value: 'Biologer, botanikere, zoologer mv.', label: 'Biologer, botanikere, zoologer mv.' },
  { value: 'Sivilagronomer mv.', label: 'Sivilagronomer mv.' },
  { value: 'Miljøvernrådgivere', label: 'Miljøvernrådgivere' },
  { value: 'Sivilingeniører (industri og produksjon)', label: 'Sivilingeniører (industri og produksjon)' },
  { value: 'Sivilingeniører (bygg og anlegg)', label: 'Sivilingeniører (bygg og anlegg)' },
  { value: 'Sivilingeniører (miljøteknikk)', label: 'Sivilingeniører (miljøteknikk)' },
  { value: 'Sivilingeniører (maskin- og marin-teknikk)', label: 'Sivilingeniører (maskin- og marin-teknikk)' },
  { value: 'Sivilingeniører (kjemi)', label: 'Sivilingeniører (kjemi)' },
  { value: 'Sivilingeniører (geofag, petro-leumsteknologi, metallurgi mv.)', label: 'Sivilingeniører (geofag, petro-leumsteknologi, metallurgi mv.)' },
  { value: 'Andre sivilingeniører (unntatt elektroteknologi)', label: 'Andre sivilingeniører (unntatt elektroteknologi)' },
  { value: 'Sivilingeniører (elkraftteknikk)', label: 'Sivilingeniører (elkraftteknikk)' },
  { value: 'Sivilingeniører (elektronikk)', label: 'Sivilingeniører (elektronikk)' },
  { value: 'Sivilingeniører (telekommunikasjon)', label: 'Sivilingeniører (telekommunikasjon)' },
  { value: 'Sivilarkitekter', label: 'Sivilarkitekter' },
  { value: 'Landskapsarkitekter', label: 'Landskapsarkitekter' },
  { value: 'Produkt- og klesdesignere', label: 'Produkt- og klesdesignere' },
  { value: 'Arealplanleggere', label: 'Arealplanleggere' },
  { value: 'Landmålere, kartografer mv.', label: 'Landmålere, kartografer mv.' },
  { value: 'Grafiske- og multimediadesignere', label: 'Grafiske- og multimediadesignere' },
  { value: 'Allmennpraktiserende leger', label: 'Allmennpraktiserende leger' },
  { value: 'Legespesialister', label: 'Legespesialister' },
  { value: 'Spesialsykepleiere', label: 'Spesialsykepleiere' },
  { value: 'Jordmødre', label: 'Jordmødre' },
  { value: 'Sykepleiere', label: 'Sykepleiere' },
  { value: 'Vernepleiere', label: 'Vernepleiere' },
  { value: 'Veterinærer', label: 'Veterinærer' },
  { value: 'Tannleger', label: 'Tannleger' },
  { value: 'Farmasøyter', label: 'Farmasøyter' },
  { value: 'Helse- og miljørådgivere', label: 'Helse- og miljørådgivere' },
  { value: 'Fysioterapeuter', label: 'Fysioterapeuter' },
  { value: 'Ernæringsfysiologer', label: 'Ernæringsfysiologer' },
  { value: 'Audiografer og logopeder', label: 'Audiografer og logopeder' },
  { value: 'Ergoterapeuter', label: 'Ergoterapeuter' },
  { value: 'Kiropraktorer mv.', label: 'Kiropraktorer mv.' },
  { value: 'Universitets- og høyskolelektorer/-lærere', label: 'Universitets- og høyskolelektorer/-lærere' },
  { value: 'Yrkesfaglærere', label: 'Yrkesfaglærere' },
  { value: 'Lektorer mv. (videregående skole)', label: 'Lektorer mv. (videregående skole)' },
  { value: 'Grunnskolelærere', label: 'Grunnskolelærere' },
  { value: 'Førskolelærere', label: 'Førskolelærere' },
  { value: 'Spesialister i pedagogikk', label: 'Spesialister i pedagogikk' },
  { value: 'Spesiallærere / spesialpedagoger', label: 'Spesiallærere / spesialpedagoger' },
  { value: 'Andre språklærere', label: 'Andre språklærere' },
  { value: 'Andre musikklærere', label: 'Andre musikklærere' },
  { value: 'Andre lærere i estetiske fag', label: 'Andre lærere i estetiske fag' },
  { value: 'Andre IKT-lærere', label: 'Andre IKT-lærere' },
  { value: 'Andre lærere', label: 'Andre lærere' },
  { value: 'Revisorer, regnskapsrådgivere', label: 'Revisorer, regnskapsrådgivere' },
  { value: 'Finans- og investeringsrådgivere', label: 'Finans- og investeringsrådgivere' },
  { value: 'Finansanalytikere', label: 'Finansanalytikere' },
  { value: 'Organisasjonsrådgivere mv.', label: 'Organisasjonsrådgivere mv.' },
  { value: 'Høyere saksbehandlere i offentlig og privat virksomhet', label: 'Høyere saksbehandlere i offentlig og privat virksomhet' },
  { value: 'Personal- og karriererådgivere', label: 'Personal- og karriererådgivere' },
  { value: 'Rådgivere innen kompetanseutvikling', label: 'Rådgivere innen kompetanseutvikling' },
  { value: 'Reklame- og markedsføringsrådgivere', label: 'Reklame- og markedsføringsrådgivere' },
  { value: 'Informasjonsrådgivere', label: 'Informasjonsrådgivere' },
  { value: 'Salgskonsulenter innen tekniske og medisinske produkter', label: 'Salgskonsulenter innen tekniske og medisinske produkter' },
  { value: 'Salgskonsulenter innen IKT-produkter', label: 'Salgskonsulenter innen IKT-produkter' },
  { value: 'Systemanalytikere/-arkitekter', label: 'Systemanalytikere/-arkitekter' },
  { value: 'Programvareutviklere', label: 'Programvareutviklere' },
  { value: 'Nett- og multimediautviklere', label: 'Nett- og multimediautviklere' },
  { value: 'Applikasjonsprogrammerere', label: 'Applikasjonsprogrammerere' },
  { value: 'Andre programvare- og applikasjonsutviklere', label: 'Andre programvare- og applikasjonsutviklere' },
  { value: 'Databasedesignere og -administratorer', label: 'Databasedesignere og -administratorer' },
  { value: 'Systemadministratorer', label: 'Systemadministratorer' },
  { value: 'Nettverksansvarlige', label: 'Nettverksansvarlige' },
  { value: 'Sikkerhetsanalytikere mv.', label: 'Sikkerhetsanalytikere mv.' },
  { value: 'Jurister og advokater', label: 'Jurister og advokater' },
  { value: 'Dommere', label: 'Dommere' },
  { value: 'Andre juridiske yrker', label: 'Andre juridiske yrker' },
  { value: 'Arkivarer og kuratorer', label: 'Arkivarer og kuratorer' },
  { value: 'Bibliotekarer og andre informasjonsarbeidere', label: 'Bibliotekarer og andre informasjonsarbeidere' },
  { value: 'Rådgivere/forskere, samfunnsøkonomi', label: 'Rådgivere/forskere, samfunnsøkonomi' },
  { value: 'Rådgivere/forskere, samfunnsvitenskap', label: 'Rådgivere/forskere, samfunnsvitenskap' },
  { value: 'Rådgivere/forskere, humanistiske fag', label: 'Rådgivere/forskere, humanistiske fag' },
  { value: 'Psykologer', label: 'Psykologer' },
  { value: 'Rådgivere innen sosiale fagfelt', label: 'Rådgivere innen sosiale fagfelt' },
  { value: 'Geistlige yrker', label: 'Geistlige yrker' },
  { value: 'Forfattere mv.', label: 'Forfattere mv.' },
  { value: 'Journalister', label: 'Journalister' },
  { value: 'Oversettere, tolker mv.', label: 'Oversettere, tolker mv.' },
  { value: 'Skulptører, kunstmalere og andre billedkunstnere', label: 'Skulptører, kunstmalere og andre billedkunstnere' },
  { value: 'Dirigenter, komponister, musikere og sangere', label: 'Dirigenter, komponister, musikere og sangere' },
  { value: 'Koreografer og dansere', label: 'Koreografer og dansere' },
  { value: 'Regissører', label: 'Regissører' },
  { value: 'Skuespillere', label: 'Skuespillere' },
  { value: 'Programledere i TV og radio', label: 'Programledere i TV og radio' },
  { value: 'Andre utøvende kunstneriske yrker', label: 'Andre utøvende kunstneriske yrker' },
  { value: 'Bygningsingeniører', label: 'Bygningsingeniører' },
  { value: 'Elkraftingeniører', label: 'Elkraftingeniører' },
  { value: 'Elektronikkingeniører', label: 'Elektronikkingeniører' },
  { value: 'Maskiningeniører', label: 'Maskiningeniører' },
  { value: 'Kjemiingeniører', label: 'Kjemiingeniører' },
  { value: 'Ingeniører innen petroleum, bergverk og metallurgi', label: 'Ingeniører innen petroleum, bergverk og metallurgi' },
  { value: 'Tekniske tegnere', label: 'Tekniske tegnere' },
  { value: 'Andre ingeniører', label: 'Andre ingeniører' },
  { value: 'Arbeidsleder, bergfag', label: 'Arbeidsleder, bergfag' },
  { value: 'Arbeidsleder, industri', label: 'Arbeidsleder, industri' },
  { value: 'Arbeidsleder, bygg og anlegg', label: 'Arbeidsleder, bygg og anlegg' },
  { value: 'Energikontrolloperatører', label: 'Energikontrolloperatører' },
  { value: 'Kontrolloperatører ved forbrennings- kjøle- og vannrenseanlegg mv.', label: 'Kontrolloperatører ved forbrennings- kjøle- og vannrenseanlegg mv.' },
  { value: 'Kontrolloperatører innen kjemisk prosessindustri', label: 'Kontrolloperatører innen kjemisk prosessindustri' },
  { value: 'Kontrolloperatører ved olje- og naturgassraffineringsanlegg', label: 'Kontrolloperatører ved olje- og naturgassraffineringsanlegg' },
  { value: 'Kontrolloperatører innen metallproduksjon', label: 'Kontrolloperatører innen metallproduksjon' },
  { value: 'Andre prosesskontrolloperatører', label: 'Andre prosesskontrolloperatører' },
  { value: 'Bioteknikere (ikke-medisinske laboratorier)', label: 'Bioteknikere (ikke-medisinske laboratorier)' },
  { value: 'Agroteknikere', label: 'Agroteknikere' },
  { value: 'Skogteknikere', label: 'Skogteknikere' },
  { value: 'Skipsmaskinister', label: 'Skipsmaskinister' },
  { value: 'Dekksoffiserer og loser', label: 'Dekksoffiserer og loser' },
  { value: 'Flygere', label: 'Flygere' },
  { value: 'Flygeledere', label: 'Flygeledere' },
  { value: 'Teknikere innen luftfartssikkerhet', label: 'Teknikere innen luftfartssikkerhet' },
  { value: 'Radiografer mv.', label: 'Radiografer mv.' },
  { value: 'Bioingeniører', label: 'Bioingeniører' },
  { value: 'Reseptarer', label: 'Reseptarer' },
  { value: 'Protese- og tannteknikere', label: 'Protese- og tannteknikere' },
  { value: 'Yrker innen alternativ medisin', label: 'Yrker innen alternativ medisin' },
  { value: 'Dyrepleiere', label: 'Dyrepleiere' },
  { value: 'Tannpleiere', label: 'Tannpleiere' },
  { value: 'Optikere', label: 'Optikere' },
  { value: 'Helsesekretærer', label: 'Helsesekretærer' },
  { value: 'Helse- og miljøkontrollører', label: 'Helse- og miljøkontrollører' },
  { value: 'Ambulansepersonell', label: 'Ambulansepersonell' },
  { value: 'Andre helseyrker', label: 'Andre helseyrker' },
  { value: 'Finansmeglere', label: 'Finansmeglere' },
  { value: 'Kundebehandlere lån og kreditt', label: 'Kundebehandlere lån og kreditt' },
  { value: 'Regnskapsførere', label: 'Regnskapsførere' },
  { value: 'Takstmenn', label: 'Takstmenn' },
  { value: 'Forsikringsagenter', label: 'Forsikringsagenter' },
  { value: 'Selgere (engros)', label: 'Selgere (engros)' },
  { value: 'Innkjøpere', label: 'Innkjøpere' },
  { value: 'Handels- og skipsmeglere', label: 'Handels- og skipsmeglere' },
  { value: 'Speditører og befraktere', label: 'Speditører og befraktere' },
  { value: 'Konferanse- og arrangementsplanleggere mv.', label: 'Konferanse- og arrangementsplanleggere mv.' },
  { value: 'Arbeidsformidlere', label: 'Arbeidsformidlere' },
  { value: 'Eiendomsmeglere og - forvaltere', label: 'Eiendomsmeglere og - forvaltere' },
  { value: 'Andre yrker innen forretningstjenester', label: 'Andre yrker innen forretningstjenester' },
  { value: 'Arbeidsledere for kontorpersonell', label: 'Arbeidsledere for kontorpersonell' },
  { value: 'Advokatsekretær', label: 'Advokatsekretær' },
  { value: 'Sjefssekretærer', label: 'Sjefssekretærer' },
  { value: 'Tollere', label: 'Tollere' },
  { value: 'Skattefunksjonærer', label: 'Skattefunksjonærer' },
  { value: 'Saksbehandlere innen sosiale ytelser', label: 'Saksbehandlere innen sosiale ytelser' },
  { value: 'Saksbehandlere for førerkort, importlisenser mv.', label: 'Saksbehandlere for førerkort, importlisenser mv.' },
  { value: 'Politibetjenter mv.', label: 'Politibetjenter mv.' },
  { value: 'Andre yrker innen offentlig forvaltning', label: 'Andre yrker innen offentlig forvaltning' },
  { value: 'Privatetterforskere mv.', label: 'Privatetterforskere mv.' },
  { value: 'Miljøarbeidere innen sosiale fagfelt', label: 'Miljøarbeidere innen sosiale fagfelt' },
  { value: 'Religiøse yrker', label: 'Religiøse yrker' },
  { value: 'Idrettsutøvere', label: 'Idrettsutøvere' },
  { value: 'Trenere og idrettsdommere', label: 'Trenere og idrettsdommere' },
  { value: 'Sports- og aktivitetsinstruktører', label: 'Sports- og aktivitetsinstruktører' },
  { value: 'Fotografer og filmfotografer', label: 'Fotografer og filmfotografer' },
  { value: 'Interiørdesignere og dekoratører', label: 'Interiørdesignere og dekoratører' },
  { value: 'Tekniske konservatorer', label: 'Tekniske konservatorer' },
  { value: 'Sjefskokker', label: 'Sjefskokker' },
  { value: 'Andre yrker innen estetiske fag', label: 'Andre yrker innen estetiske fag' },
  { value: 'Driftsteknikere, IKT', label: 'Driftsteknikere, IKT' },
  { value: 'Brukerstøtte, IKT', label: 'Brukerstøtte, IKT' },
  { value: 'Nettverks- og systemteknikere, IKT', label: 'Nettverks- og systemteknikere, IKT' },
  { value: 'Internett-teknikere', label: 'Internett-teknikere' },
  { value: 'Teknikere innen radio og tv', label: 'Teknikere innen radio og tv' },
  { value: 'Teknikere innen telekom', label: 'Teknikere innen telekom' },
  { value: 'Kontormedarbeidere', label: 'Kontormedarbeidere' },
  { value: 'Stenografer mv.', label: 'Stenografer mv.' },
  { value: 'Dataregistrere', label: 'Dataregistrere' },
  { value: 'Kundebehandlere, bank og postkontor', label: 'Kundebehandlere, bank og postkontor' },
  { value: 'Bingoverter, bookmakere mv.', label: 'Bingoverter, bookmakere mv.' },
  { value: 'Pantelånere mv.', label: 'Pantelånere mv.' },
  { value: 'Inkassomedarbeidere mv.', label: 'Inkassomedarbeidere mv.' },
  { value: 'Reisebyråmedarbeidere mv.', label: 'Reisebyråmedarbeidere mv.' },
  { value: 'Kundesentermedarbeidere', label: 'Kundesentermedarbeidere' },
  { value: 'Sentralbordoperatører', label: 'Sentralbordoperatører' },
  { value: 'Hotellresepsjonister', label: 'Hotellresepsjonister' },
  { value: 'Informasjonsskrankemedarbeidere', label: 'Informasjonsskrankemedarbeidere' },
  { value: 'Resepsjonister (ekskl. hotell)', label: 'Resepsjonister (ekskl. hotell)' },
  { value: 'Intervjuere', label: 'Intervjuere' },
  { value: 'Andre opplysningsmedarbeidere', label: 'Andre opplysningsmedarbeidere' },
  { value: 'Regnskapsmedarbeidere', label: 'Regnskapsmedarbeidere' },
  { value: 'Forsikrings- og finansmedarbeidere', label: 'Forsikrings- og finansmedarbeidere' },
  { value: 'Lønningsmedarbeidere', label: 'Lønningsmedarbeidere' },
  { value: 'Lagermedarbeidere og material-forvaltere', label: 'Lagermedarbeidere og material-forvaltere' },
  { value: 'Logistikkmedarbeidere', label: 'Logistikkmedarbeidere' },
  { value: 'Transportfunksjonærer', label: 'Transportfunksjonærer' },
  { value: 'Bibliotekassistenter', label: 'Bibliotekassistenter' },
  { value: 'Postbud og postsorterere', label: 'Postbud og postsorterere' },
  { value: 'Kodere mv.', label: 'Kodere mv.' },
  { value: 'Arkivassistenter', label: 'Arkivassistenter' },
  { value: 'Personalkontormedarbeidere', label: 'Personalkontormedarbeidere' },
  { value: 'Flyverter, båtverter mv.', label: 'Flyverter, båtverter mv.' },
  { value: 'Konduktører', label: 'Konduktører' },
  { value: 'Reiseledere og guider', label: 'Reiseledere og guider' },
  { value: 'Kokker', label: 'Kokker' },
  { value: 'Servitører', label: 'Servitører' },
  { value: 'Bartendere', label: 'Bartendere' },
  { value: 'Frisører', label: 'Frisører' },
  { value: 'Kosmetologer mv.', label: 'Kosmetologer mv.' },
  { value: 'Renholdsledere i virksomheter', label: 'Renholdsledere i virksomheter' },
  { value: 'Husholdere', label: 'Husholdere' },
  { value: 'Vaktmestre', label: 'Vaktmestre' },
  { value: 'Astrologer mv.', label: 'Astrologer mv.' },
  { value: 'Begravelsesbyrå- og krematoriearbeidere', label: 'Begravelsesbyrå- og krematoriearbeidere' },
  { value: 'Dyrepassere og - trenere mv.', label: 'Dyrepassere og - trenere mv.' },
  { value: 'Kjøreskolelærere', label: 'Kjøreskolelærere' },
  { value: 'Andre personlige tjenesteytere', label: 'Andre personlige tjenesteytere' },
  { value: 'Torghandlere', label: 'Torghandlere' },
  { value: 'Gateselgere, mat', label: 'Gateselgere, mat' },
  { value: 'Innehavere av kiosk/liten butikk', label: 'Innehavere av kiosk/liten butikk' },
  { value: 'Butikkavdelingssjefer', label: 'Butikkavdelingssjefer' },
  { value: 'Butikkmedarbeidere', label: 'Butikkmedarbeidere' },
  { value: 'Billettselgere', label: 'Billettselgere' },
  { value: 'Mannekenger og modeller', label: 'Mannekenger og modeller' },
  { value: 'Demonstrasjonsselgere', label: 'Demonstrasjonsselgere' },
  { value: 'Dørselgere', label: 'Dørselgere' },
  { value: 'Telefon- og nettselgere', label: 'Telefon- og nettselgere' },
  { value: 'Servicemedarbeidere (bensinstasjon)', label: 'Servicemedarbeidere (bensinstasjon)' },
  { value: 'Gatekjøkken- og kafémedarbeidere mv.', label: 'Gatekjøkken- og kafémedarbeidere mv.' },
  { value: 'Andre salgsmedarbeidere', label: 'Andre salgsmedarbeidere' },
  { value: 'Barnehage- og skolefritidsassistenter mv.', label: 'Barnehage- og skolefritidsassistenter mv.' },
  { value: 'Skoleassistenter', label: 'Skoleassistenter' },
  { value: 'Helsefagarbeidere', label: 'Helsefagarbeidere' },
  { value: 'Hjemmehjelper', label: 'Hjemmehjelper' },
  { value: 'Andre pleiemedarbeidere', label: 'Andre pleiemedarbeidere' },
  { value: 'Brannkonstabler', label: 'Brannkonstabler' },
  { value: 'Fengselsbetjenter', label: 'Fengselsbetjenter' },
  { value: 'Vektere', label: 'Vektere' },
  { value: 'Andre sikkerhetsarbeidere', label: 'Andre sikkerhetsarbeidere' },
  { value: 'Korn- og grønnsaksprodusenter', label: 'Korn- og grønnsaksprodusenter' },
  { value: 'Frukt- og bærprodusenter', label: 'Frukt- og bærprodusenter' },
  { value: 'Gartnere', label: 'Gartnere' },
  { value: 'Kombinasjonsbrukere, nyttevekster', label: 'Kombinasjonsbrukere, nyttevekster' },
  { value: 'Melke- og husdyrprodusenter', label: 'Melke- og husdyrprodusenter' },
  { value: 'Egg- og fjærfeprodusenter', label: 'Egg- og fjærfeprodusenter' },
  { value: 'Birøktere mv.', label: 'Birøktere mv.' },
  { value: 'Andre dyreoppdrettere og røktere', label: 'Andre dyreoppdrettere og røktere' },
  { value: 'Plante- og husdyrprodusenter (kombinasjonsbruk)', label: 'Plante- og husdyrprodusenter (kombinasjonsbruk)' },
  { value: 'Skogbrukere', label: 'Skogbrukere' },
  { value: 'Havbruksarbeidere', label: 'Havbruksarbeidere' },
  { value: 'Fiskere', label: 'Fiskere' },
  { value: 'Fangstfolk', label: 'Fangstfolk' },
  { value: 'Murere', label: 'Murere' },
  { value: 'Steinhoggere mv.', label: 'Steinhoggere mv.' },
  { value: 'Betongarbeidere', label: 'Betongarbeidere' },
  { value: 'Tømrere og snekkere', label: 'Tømrere og snekkere' },
  { value: 'Andre bygningsarbeidere', label: 'Andre bygningsarbeidere' },
  { value: 'Taktekkere', label: 'Taktekkere' },
  { value: 'Gulv- og flisleggere', label: 'Gulv- og flisleggere' },
  { value: 'Gips- og sparklingsarbeidere', label: 'Gips- og sparklingsarbeidere' },
  { value: 'Isolatører mv.', label: 'Isolatører mv.' },
  { value: 'Glassarbeidere', label: 'Glassarbeidere' },
  { value: 'Rørleggere og VVS-montører', label: 'Rørleggere og VVS-montører' },
  { value: 'Kuldemontører mv.', label: 'Kuldemontører mv.' },
  { value: 'Malere og byggtapetserere', label: 'Malere og byggtapetserere' },
  { value: 'Overflatebehandlere og lakkerere', label: 'Overflatebehandlere og lakkerere' },
  { value: 'Feiere, fasaderenholdere mv.', label: 'Feiere, fasaderenholdere mv.' },
  { value: 'Støpere', label: 'Støpere' },
  { value: 'Sveisere', label: 'Sveisere' },
  { value: 'Kopper- og blikkenslagere', label: 'Kopper- og blikkenslagere' },
  { value: 'Platearbeidere', label: 'Platearbeidere' },
  { value: 'Riggere og spleisere', label: 'Riggere og spleisere' },
  { value: 'Smeder', label: 'Smeder' },
  { value: 'Verktøymaker, låsesmeder mv.', label: 'Verktøymaker, låsesmeder mv.' },
  { value: 'Metalldreiere mv.', label: 'Metalldreiere mv.' },
  { value: 'Metallslipere', label: 'Metallslipere' },
  { value: 'Bilmekanikere', label: 'Bilmekanikere' },
  { value: 'Mekanikere innen flytekniske fag', label: 'Mekanikere innen flytekniske fag' },
  { value: 'Anleggsmaskin- og industrimekanikere', label: 'Anleggsmaskin- og industrimekanikere' },
  { value: 'Sykkelreparatører mv.', label: 'Sykkelreparatører mv.' },
  { value: 'Presisjonsinstrumentmakere og -reparatører', label: 'Presisjonsinstrumentmakere og -reparatører' },
  { value: 'Musikkinstrumentmakere og -stemmere', label: 'Musikkinstrumentmakere og -stemmere' },
  { value: 'Gull- og sølvsmeder, gravører mv.', label: 'Gull- og sølvsmeder, gravører mv.' },
  { value: 'Keramikere mv.', label: 'Keramikere mv.' },
  { value: 'Glasshåndverkere', label: 'Glasshåndverkere' },
  { value: 'Dekormalere mv.', label: 'Dekormalere mv.' },
  { value: 'Kunsthåndverkere i tre mv.', label: 'Kunsthåndverkere i tre mv.' },
  { value: 'Vevere, strikkere mv. (innen husflidsproduksjon)', label: 'Vevere, strikkere mv. (innen husflidsproduksjon)' },
  { value: 'Andre kunsthåndverkere', label: 'Andre kunsthåndverkere' },
  { value: 'Førtrykkere', label: 'Førtrykkere' },
  { value: 'Trykkere', label: 'Trykkere' },
  { value: 'Innbindere mv.', label: 'Innbindere mv.' },
  { value: 'Elektrikere', label: 'Elektrikere' },
  { value: 'Automatikere', label: 'Automatikere' },
  { value: 'Energimontører', label: 'Energimontører' },
  { value: 'Serviceelektronikere', label: 'Serviceelektronikere' },
  { value: 'Tele- og IKT-installatører', label: 'Tele- og IKT-installatører' },
  { value: 'Slaktere, fiskehandlere mv.', label: 'Slaktere, fiskehandlere mv.' },
  { value: 'Bakere, konditorer mv.', label: 'Bakere, konditorer mv.' },
  { value: 'Ystere mv. (gårdsproduksjon)', label: 'Ystere mv. (gårdsproduksjon)' },
  { value: 'Saftere, syltere mv. (gårdsproduksjon)', label: 'Saftere, syltere mv. (gårdsproduksjon)' },
  { value: 'Prøvesmakere og kvalitetsbedømmere av mat og drikke', label: 'Prøvesmakere og kvalitetsbedømmere av mat og drikke' },
  { value: 'Møbelsnekkere', label: 'Møbelsnekkere' },
  { value: 'Skreddere, buntmakere mv.', label: 'Skreddere, buntmakere mv.' },
  { value: 'Gradører', label: 'Gradører' },
  { value: 'Møbeltapetserere mv.', label: 'Møbeltapetserere mv.' },
  { value: 'Skinnberedere og garvere', label: 'Skinnberedere og garvere' },
  { value: 'Skomakere', label: 'Skomakere' },
  { value: 'Yrkesdykkere', label: 'Yrkesdykkere' },
  { value: 'Skytebaser og sprengningsarbeidere', label: 'Skytebaser og sprengningsarbeidere' },
  { value: 'Produkttestere (ikke matprodukter)', label: 'Produkttestere (ikke matprodukter)' },
  { value: 'Desinfeksjonsarbeidere og skadedyrbekjempere', label: 'Desinfeksjonsarbeidere og skadedyrbekjempere' },
  { value: 'Andre håndverkere', label: 'Andre håndverkere' },
  { value: 'Bergfagarbeidere', label: 'Bergfagarbeidere' },
  { value: 'Prosessoperatører (oppredning)', label: 'Prosessoperatører (oppredning)' },
  { value: 'Operatører innen boring mv.', label: 'Operatører innen boring mv.' },
  { value: 'Operatører innen produksjon av betong mv.', label: 'Operatører innen produksjon av betong mv.' },
  { value: 'Operatører innen metallurgiske prosessfag', label: 'Operatører innen metallurgiske prosessfag' },
  { value: 'Operatører innen metallflatebehandling', label: 'Operatører innen metallflatebehandling' },
  { value: 'Operatører innen kjemisk industri', label: 'Operatører innen kjemisk industri' },
  { value: 'Operatører innen produksjon av fotofilm og -papir mv.', label: 'Operatører innen produksjon av fotofilm og -papir mv.' },
  { value: 'Operatører innen produksjon av gummiprodukter', label: 'Operatører innen produksjon av gummiprodukter' },
  { value: 'Operatører innen plastprodukter', label: 'Operatører innen plastprodukter' },
  { value: 'Operatører innen papirprodukter', label: 'Operatører innen papirprodukter' },
  { value: 'Spinne- og nøstemaskinoperatører', label: 'Spinne- og nøstemaskinoperatører' },
  { value: 'Operatører innen tekstilproduksjon mv.', label: 'Operatører innen tekstilproduksjon mv.' },
  { value: 'Industrisyere', label: 'Industrisyere' },
  { value: 'Operatører innen tekstilbearbeiding', label: 'Operatører innen tekstilbearbeiding' },
  { value: 'Operatører innen pels, skinn- og lærbearbeiding', label: 'Operatører innen pels, skinn- og lærbearbeiding' },
  { value: 'Operatører innen skinn og lærprodukter', label: 'Operatører innen skinn og lærprodukter' },
  { value: 'Renseri- og vaskerimaskinoperatører', label: 'Renseri- og vaskerimaskinoperatører' },
  { value: 'Andre operatører innen produksjon av tekstiler, pels, skinn og lær', label: 'Andre operatører innen produksjon av tekstiler, pels, skinn og lær' },
  { value: 'Operatører innen næringsmiddelproduksjon', label: 'Operatører innen næringsmiddelproduksjon' },
  { value: 'Operatører innen treforedling', label: 'Operatører innen treforedling' },
  { value: 'Operatører innen trelastproduksjon', label: 'Operatører innen trelastproduksjon' },
  { value: 'Operatører innen glass- og keramisk produksjon', label: 'Operatører innen glass- og keramisk produksjon' },
  { value: 'Fyrkjele- og turbinoperatører', label: 'Fyrkjele- og turbinoperatører' },
  { value: 'Pakke-, tappe- og etikettmaskinoperatører', label: 'Pakke-, tappe- og etikettmaskinoperatører' },
  { value: 'Andre stasjonære maskinoperatører', label: 'Andre stasjonære maskinoperatører' },
  { value: 'Montører av mekaniske produkter', label: 'Montører av mekaniske produkter' },
  { value: 'Montører av elektriske og elektroniske produkter', label: 'Montører av elektriske og elektroniske produkter' },
  { value: 'Andre montører', label: 'Andre montører' },
  { value: 'Lokomotiv og T-baneførere', label: 'Lokomotiv og T-baneførere' },
  { value: 'Skiftekonduktører mv', label: 'Skiftekonduktører mv' },
  { value: 'Bil-, drosje- og varebilførere', label: 'Bil-, drosje- og varebilførere' },
  { value: 'Bussjåfører og trikkeførere', label: 'Bussjåfører og trikkeførere' },
  { value: 'Lastebil- og trailersjåfører', label: 'Lastebil- og trailersjåfører' },
  { value: 'Jordbruks- og skogbruksmaskinførere', label: 'Jordbruks- og skogbruksmaskinførere' },
  { value: 'Anleggsmaskinførere', label: 'Anleggsmaskinførere' },
  { value: 'Kran- og heisførere mv.', label: 'Kran- og heisførere mv.' },
  { value: 'Truckførere', label: 'Truckførere' },
  { value: 'Dekks- og maskinmannskap (skip)', label: 'Dekks- og maskinmannskap (skip)' },
  { value: 'Renholdere i private hjem', label: 'Renholdere i private hjem' },
  { value: 'Renholdere i virksomheter', label: 'Renholdere i virksomheter' },
  { value: 'Bilvaskere', label: 'Bilvaskere' },
  { value: 'Vinduspussere', label: 'Vinduspussere' },
  { value: 'Andre rengjørere', label: 'Andre rengjørere' },
  { value: 'Hjelpearbeidere i nyttevekstproduksjon', label: 'Hjelpearbeidere i nyttevekstproduksjon' },
  { value: 'Hjelpearbeidere i husdyrproduksjon', label: 'Hjelpearbeidere i husdyrproduksjon' },
  { value: 'Hjelpearbeidere i kombinasjonsbruk', label: 'Hjelpearbeidere i kombinasjonsbruk' },
  { value: 'Hjelpearbeidere i gartneri mv.', label: 'Hjelpearbeidere i gartneri mv.' },
  { value: 'Hjelpearbeidere i skogbruk', label: 'Hjelpearbeidere i skogbruk' },
  { value: 'Hjelpearbeidere innen havbruk', label: 'Hjelpearbeidere innen havbruk' },
  { value: 'Hjelpearbeidere i bergverk', label: 'Hjelpearbeidere i bergverk' },
  { value: 'Hjelpearbeidere i anlegg', label: 'Hjelpearbeidere i anlegg' },
  { value: 'Hjelpearbeidere i bygg', label: 'Hjelpearbeidere i bygg' },
  { value: 'Håndpakkere mv.', label: 'Håndpakkere mv.' },
  { value: 'Andre hjelpearbeidere i industri', label: 'Andre hjelpearbeidere i industri' },
  { value: 'Førere av ikke-motorisert kjøretøy', label: 'Førere av ikke-motorisert kjøretøy' },
  { value: 'Laste- og lossearbeidere', label: 'Laste- og lossearbeidere' },
  { value: 'Varepåfyllere', label: 'Varepåfyllere' },
  { value: 'Kjøkkenassistenter', label: 'Kjøkkenassistenter' },
  { value: 'Reklamedistributører mv.', label: 'Reklamedistributører mv.' },
  { value: 'Renovasjonsarbeidere', label: 'Renovasjonsarbeidere' },
  { value: 'Gjenvinningsarbeidere', label: 'Gjenvinningsarbeidere' },
  { value: 'Gatefeiere mv.', label: 'Gatefeiere mv.' },
  { value: 'Bud mv.', label: 'Bud mv.' },
  { value: 'Altmuligmann', label: 'Altmuligmann' },
  { value: 'Måleravlesere mv.', label: 'Måleravlesere mv.' },
  { value: 'Andre hjelpearbeidere', label: 'Andre hjelpearbeidere' }
]

export default stillingstitler;
