const rolletyper: any = {
  'elevEllerStudent': {
    'isArbeidstaker': false,
    'isLaerling': false,
    'isElevEllerStudent': true,
    'showStillinger': false,
    'showWorkplace': false,
    'showAccidentBackground': false,
    'showAccidentPlace': true,
    'showAbsence': false,
    'showAccidentPlacePage': true,
    'showServicePeriode':false,
    'showServiceDepartment': false,
  },
  'arbeidstaker': {
    'isArbeidstaker': true,
    'isLaerling': false,
    'isElevEllerStudent': false,
    'showStillinger': true,
    'showWorkplace': true,
    'showAccidentPlace': true,
    'showAccidentBackground': true,
    'showAbsence': true,
    'showAccidentPlacePage': true,
    'showServicePeriode':false,
    'showServiceDepartment': false,
  },
  'laerling': {
    'isArbeidstaker': true,
    'isLaerling': true,
    'isElevEllerStudent': false,
    'showStillinger': true,
    'showWorkplace': true,
    'showAccidentBackground': true,
    'showAbsence': true,
    'showAccidentPlace': true,
    'showAccidentPlacePage': true,
    'showServicePeriode':false,
    'showServiceDepartment': false,
  },
  'tiltaksdeltaker': {
    'showStillinger': false,
    'showWorkplace': true,
    'showAccidentBackground': true,
    'showAbsence': false,
    'showAccidentPlace': true,
    'showAccidentPlacePage': true,
    'showServicePeriode':false,
    'showServiceDepartment': false,
  },
  'vernepliktigIFoerstegangstjenesten': {
    'isArbeidstaker': false,
    'isLaerling': false,
    'isElevEllerStudent': true,
    'showStillinger': false,
    'showWorkplace': false,
    'showAccidentBackground': false,
    'showAbsence': false,
    'showAccidentPlace': true,
    'showAccidentPlacePage': false,
    'showServicePeriode':true,
    'showServiceDepartment': true,
  },
  'redningsEllerBranntjenesteUtenforArbeidsforhold': {
    'showStillinger': false,
    'showWorkplace': false,
    'showAccidentBackground': true,
    'showAccidentPlace': false,
    'showAbsence': false,
    'showAccidentPlacePage': true,
    'showServicePeriode':false,
    'showServiceDepartment': false,
  }
}

export default rolletyper;
