const rolletyper: any = {
  'elevEllerStudent': {
    'showAbsence': false,
    'showAccidentBackground': false,
    'showAccidentPlace': true,
    'showAccidentPlacePage': true,
    'showAdress': true,
    'showServiceDepartment': false,
    'showServicePeriode': false,
    'showStillinger': false,
    'showTimeframeWhenInjuredPeriod': true,
    'showWorkplace': false
  },
  'arbeidstaker': {
    'showAbsence': true,
    'showAccidentBackground': true,
    'showAccidentPlace': true,
    'showAccidentPlacePage': true,
    'showAdress': true,
    'showServiceDepartment': false,
    'showServicePeriode': false,
    'showStillinger': true,
    'showTimeframeWhenInjuredPeriod': true,
    'showWorkplace': true
  },
  'laerling': {
    'showAbsence': true,
    'showAccidentBackground': true,
    'showAccidentPlace': true,
    'showAccidentPlacePage': true,
    'showAdress': true,
    'showServiceDepartment': false,
    'showServicePeriode': false,
    'showStillinger': true,
    'showTimeframeWhenInjuredPeriod': true,
    'showWorkplace': true
  },
  'tiltaksdeltaker': {
    'showAbsence': false,
    'showAccidentBackground': true,
    'showAccidentPlace': true,
    'showAccidentPlacePage': true,
    'showAdress': true,
    'showServiceDepartment': false,
    'showServicePeriode': false,
    'showStillinger': false,
    'showTimeframeWhenInjuredPeriod': true,
    'showWorkplace': true,
  },
  'branntjenesteUtenforArbeidsforhold': {
    'showAbsence': false,
    'showAccidentBackground': true,
    'showAccidentPlace': false,
    'showAccidentPlacePage': true,
    'showServiceDepartment': false,
    'showServicePeriode': false,
    'showStillinger': false,
    'showTimeframeWhenInjuredPeriod': true,
    'showWorkplace': false
  },
  'privatpersonSomUtfoererLivredningEllerAvvergerMaterielleTap': {
    'showAbsence': false,
    'showAccidentBackground': true,
    'showAccidentPlace': false,
    'showAccidentPlacePage': true,
    'showServiceDepartment': false,
    'showServicePeriode': false,
    'showStillinger': false,
    'showTimeframeWhenInjuredPeriod': true,
    'showWorkplace': false
  },
  'redningspersonellIOrganisasjonerOgForeninger': {
    'showAbsence': false,
    'showAccidentBackground': true,
    'showAccidentPlace': false,
    'showAccidentPlacePage': true,
    'showServiceDepartment': false,
    'showServicePeriode': false,
    'showStillinger': false,
    'showTimeframeWhenInjuredPeriod': true,
    'showWorkplace': false
  },
  'militaerTilsatt': {
    'showAbsence': false,
    'showAccidentBackground': false,
    'showAccidentPlace': true,
    'showAccidentPlacePage': true,
    'showAdress': false,
    'showEducationStarted': false,
    'showOrderManeuver': true,
    'showServiceDepartment': true,
    'showServicePeriode': false,
    'showStillinger': false,
    'showTimeframeWhenInjuredPeriod': false,
    'showWorkplace': false
  },
  'militaerLaerling': {
    'showAbsence': false,
    'showAccidentBackground': false,
    'showAccidentPlace': true,
    'showAccidentPlacePage': true,
    'showAdress': false,
    'showEducationStarted': true,
    'showOrderManeuver': true,
    'showServiceDepartment': true,
    'showServicePeriode': false,
    'showStillinger': false,
    'showTimeframeWhenInjuredPeriod': false,
    'showWorkplace': false
  },
  'militaerElev': {
    'showAbsence': false,
    'showAccidentBackground': false,
    'showAccidentPlace': true,
    'showAccidentPlacePage': true,
    'showAdress': false,
    'showEducationStarted': true,
    'showOrderManeuver': true,
    'showServiceDepartment': true,
    'showServicePeriode': false,
    'showStillinger': false,
    'showTimeframeWhenInjuredPeriod': false,
    'showWorkplace': false
  },
  'vernepliktigIRepetisjonstjeneste': {
    'showAbsence': false,
    'showAccidentBackground': false,
    'showAccidentPlace': true,
    'showAccidentPlacePage': false,
    'showAdress': false,
    'showEducationStarted': false,
    'showOrderManeuver': false,
    'showServiceDepartment': true,
    'showServicePeriode': true,
    'showStillinger': false,
    'showTimeframeWhenInjuredPeriod': true,
    'showWorkplace': false,
  },
  'frivilligTjenestegjoerendeIForsvaret': {
    'showAbsence': false,
    'showAccidentBackground': false,
    'showAccidentPlace': true,
    'showAccidentPlacePage': false,
    'showAdress': false,
    'showEducationStarted': false,
    'showOrderManeuver': false,
    'showServiceDepartment': true,
    'showServicePeriode': true,
    'showStillinger': false,
    'showTimeframeWhenInjuredPeriod': true,
    'showWorkplace': false
  },
  'vernepliktigIFoerstegangstjenesten': {
    'showAbsence': false,
    'showAccidentBackground': false,
    'showAccidentPlace': true,
    'showAccidentPlacePage': false,
    'showAdress': false,
    'showEducationStarted': false,
    'showOrderManeuver': false,
    'showServiceDepartment': true,
    'showServicePeriode': true,
    'showStillinger': false,
    'showTimeframeWhenInjuredPeriod': true,
    'showWorkplace': false,
  }
}

export default rolletyper;
