export const endpointUrls = {
  innlogget: '**/yrkesskade/innlogget',
  skademelding: '**/api/*/skademeldinger',
  brukerinfo: '**/api/*/brukerinfo',
  brukerinfoOrganisasjon: '**/api/*/brukerinfo/organisasjoner/*',
  brukerinfoRoller: '**/api/*/brukerinfo/organisasjoner/*/roller',
  toggle: '**/yrkesskade/toggles',
  log: '**/log',
  print: '**/print*',
  landkoder: '**/api/*/kodeverk/typer/landkoder/kategorier/*/kodeverdier',
  tidsromkoder: '**/api/*/kodeverk/typer/tidsrom/kategorier/*/kodeverdier',
  kodeverk: (kodeverk: string) => `**/api/*/kodeverk/typer/${kodeverk}/kategorier/*/kodeverdier`,
  kodeverkUtenKategori: (kodeverk: string) => `**/api/*/kodeverk/typer/${kodeverk}/kodeverdier`,
  amplitude: '**/collect-auto',
};
