export const endpointUrls = {
  innlogget: '**/yrkesskade/innlogget',
  skademelding: '**/api/*/skademeldinger',
  brukerinfo: '**/api/*/brukerinfo',
  brukerinfoOrganisasjon: (organisasjonsnummer: string) => `**/api/*/brukerinfo/organisasjoner/${organisasjonsnummer}`,
  brukerinfoRoller: (organisasjonsnummer: string) => `**/api/*/brukerinfo/organisasjoner/${organisasjonsnummer}/roller`,
  toggle: '**/yrkesskade/toggles',
  log: '**/log',
  print: '**/print*',
  landkoder: '**/api/*/kodeverk/typer/landkoder/kategorier/*/kodeverdier',
  tidsromkoder: '**/api/*/kodeverk/typer/tidsrom/kategorier/*/kodeverdier',
  kodeverk: (kodeverk: string) => `**/api/*/kodeverk/typer/${kodeverk}/kategorier/*/kodeverdier`,
  kodeverkUtenKategori: (kodeverk: string) => `**/api/*/kodeverk/typer/${kodeverk}/kodeverdier`,
  amplitude: '**/collect-auto',
};
