name: Cypress Tests

on:
  push:
    branches-ignore:
      - main # deploy-dev.yml har egen cypress test

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: "actions/setup-node@v2"
        with:
          node-version: "14"
          cache: "yarn"
      - name: "install server dependencies Yarn"
        # if: "steps.cache-server-node-modules.outputs.cache-hit != 'true'"
        run: "yarn client install --frozen-lockfile"
      - name: "install client dependencies Yarn"
        run: "yarn install --frozen-lockfile"
        working-directory: "client"
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn dev
          wait-on: 'http://localhost:3001'
